# Generated by Django 4.1.6 on 2023-02-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.TextField(max_length=1000)),
                ('nationality', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('institute_url', models.URLField()),
                ('course_of_study', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('final_grade', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('major_field', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='core.contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='core.socialmedia'),
        ),
    ]
