# Generated by Django 4.1.6 on 2023-02-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0002_contact_slogan")]

    operations = [
        migrations.CreateModel(
            name="Interests",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="interests", to="core.contact"
                    ),
                ),
            ],
        )
    ]
