# Generated by Django 4.1.6 on 2023-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0004_education_is_current")]

    operations = [
        migrations.AlterField(
            model_name="education", name="description", field=models.TextField(blank=True, max_length=2000, null=True)
        ),
        migrations.AlterField(model_name="education", name="end_date", field=models.DateField(blank=True, null=True)),
        migrations.AlterField(
            model_name="education", name="final_grade", field=models.CharField(blank=True, max_length=10, null=True)
        ),
        migrations.AlterField(
            model_name="education", name="institute_url", field=models.URLField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="education", name="major_field", field=models.CharField(blank=True, max_length=50, null=True)
        ),
    ]
