# Generated by Django 4.1.6 on 2023-02-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0007_skill_contact_skills")]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("is_percentage", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(model_name="skill", name="percentage", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="core.skillcategory",
            ),
        ),
    ]
