# Generated by Django 4.1.6 on 2023-02-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0011_message")]

    operations = [
        migrations.AddField(
            model_name="education",
            name="institute_logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/logos"),
        ),
        migrations.AddField(
            model_name="interests",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/icons"),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/logos"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="credential_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/certificates"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="images/profile_pics"),
        ),
    ]
