# Generated by Django 4.1.6 on 2023-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0012_education_institute_logo_interests_image_and_more")]

    operations = [
        migrations.AddField(model_name="socialmedia", name="add_to_menu", field=models.BooleanField(default=False))
    ]
