# Generated by Django 4.1.6 on 2023-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0013_socialmedia_add_to_menu")]

    operations = [
        migrations.AlterField(
            model_name="contact", name="address", field=models.TextField(blank=True, max_length=1000, null=True)
        ),
        migrations.AlterField(model_name="contact", name="birthdate", field=models.DateField(blank=True, null=True)),
        migrations.AlterField(
            model_name="contact", name="description", field=models.TextField(blank=True, max_length=2000, null=True)
        ),
        migrations.AlterField(
            model_name="contact", name="email", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(blank=True, choices=[("F", "Female"), ("M", "Male")], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="contact", name="lastname", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="contact", name="nationality", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="contact", name="phone", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile_pics"),
        ),
        migrations.AlterField(
            model_name="contact", name="skills", field=models.ManyToManyField(blank=True, null=True, to="core.skill")
        ),
        migrations.AlterField(
            model_name="contact", name="slogan", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="contact",
            name="social_media",
            field=models.ManyToManyField(blank=True, null=True, to="core.socialmedia"),
        ),
        migrations.AlterField(
            model_name="contact", name="website", field=models.CharField(blank=True, max_length=100, null=True)
        ),
    ]
