# Generated by Django 4.1.6 on 2023-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0015_auto_20230303_2110")]

    operations = [
        migrations.AlterField(model_name="contact", name="skills", field=models.ManyToManyField(to="core.skill")),
        migrations.AlterField(
            model_name="contact", name="social_media", field=models.ManyToManyField(to="core.socialmedia")
        ),
    ]
