# Generated by Django 4.1.6 on 2023-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0003_message")]

    operations = [migrations.AddField(model_name="message", name="date", field=models.DateField(auto_now=True))]
