# Generated by Django 4.1.6 on 2023-02-24 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("blog", "0004_message_date")]

    operations = [migrations.DeleteModel(name="Message")]
