# Generated by Django 4.1.6 on 2023-02-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("stars", models.IntegerField(blank=True, null=True)),
                ("forks", models.IntegerField(blank=True, null=True)),
                ("contributions", models.IntegerField(blank=True, null=True)),
                ("repositories", models.IntegerField(blank=True, null=True)),
                ("loc_added", models.IntegerField(blank=True, null=True)),
                ("loc_deleted", models.IntegerField(blank=True, null=True)),
                ("loc_changed", models.IntegerField(blank=True, null=True)),
                ("page_views", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Languages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("percentage", models.FloatField(blank=True, null=True)),
                (
                    "stat",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="github.stats"
                    ),
                ),
            ],
        ),
    ]
