# Generated by Django 4.1.6 on 2023-02-26 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("github", "0002_githubuser_stats_user")]

    operations = [migrations.RenameModel(old_name="Stats", new_name="UserStats")]
