# Generated by Django 4.1.6 on 2023-02-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("github", "0003_rename_stats_userstats")]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("occurences", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("prop", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="userstats", name="user"),
        migrations.AddField(
            model_name="githubuser",
            name="stats",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="github.userstats"
            ),
        ),
        migrations.DeleteModel(name="Languages"),
        migrations.AddField(
            model_name="language",
            name="stat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language",
                to="github.userstats",
            ),
        ),
    ]
