# Generated by Django 4.1.6 on 2023-02-26 22:59

from django.db import migrations, models
import django.db.models.deletion
import github.models


class Migration(migrations.Migration):
    dependencies = [("github", "0004_language_remove_userstats_user_githubuser_stats_and_more")]

    operations = [
        migrations.RemoveField(model_name="userstats", name="loc_changed"),
        migrations.AlterField(
            model_name="githubuser",
            name="stats",
            field=models.OneToOneField(
                blank=True,
                default=github.models.default_stats,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="github.userstats",
            ),
        ),
    ]
