# Generated by Django 4.1.6 on 2023-02-26 23:00

from django.db import migrations, models
import django.db.models.deletion
import github.models


class Migration(migrations.Migration):
    dependencies = [("github", "0005_remove_userstats_loc_changed_alter_githubuser_stats")]

    operations = [
        migrations.AlterField(
            model_name="githubuser",
            name="stats",
            field=models.OneToOneField(
                default=github.models.default_stats, on_delete=django.db.models.deletion.CASCADE, to="github.userstats"
            ),
        )
    ]
