# Generated by Django 4.1.6 on 2023-03-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_education_institute_logo_interests_image_and_more"),
        ("github", "0006_alter_githubuser_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubuser",
            name="contact",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="github_user", to="core.contact"
            ),
            preserve_default=False,
        )
    ]
