# Generated by Django 4.1.6 on 2023-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("github", "0007_githubuser_contact")]

    operations = [
        migrations.AddField(model_name="userstats", name="last_updated", field=models.DateTimeField(auto_now=True))
    ]
